[Do not merge] add benchmarks to pipeline
paritytech/cumulus pull request #1074
Opened 2022-03-09 10:06 UTC by alvicsam

Part of https://github.com/paritytech/ci_cd/issues/260

2022-04-04 13:57 UTC, TriplEight requested changes

2022-04-04 13:57 UTC, TriplEight commented on .gitlab-ci.yml
> +  - benchmarks
```suggestion
  - benchmarks-run
```

2022-04-04 13:57 UTC, TriplEight commented on .gitlab-ci.yml
> +  stage:                           benchmarks
```suggestion
  stage:                           benchmarks-run
```

2022-04-04 13:59 UTC, TriplEight approved these changes

2022-04-07 15:24 UTC, alvicsam commented
There is an additional condition that should be implemented (after discussing it with @NachoPal in element):

Weights should be pushed to the same branch where the binary for benchmarks was compiled.

Example:

1. Select branch release-parachains-vX.Y.Z -> Click Run benchmarks button
2. The binary is built, benchmarks are run.
3. When the new weights are ready, a PR is open against release-parachains-vX.Y.Z
4. We review the PR and merge it to release-parachains-vX.Y.Z

2022-04-07 15:30 UTC, NachoPal requested changes
Thanks @alvicsam . I realised that we'll need an input to select the branch we want to use for building the binary, running the benchmarks and opening a PR with the new weights.

The flow would be as follows:
1. Select branch release-parachains-vX.Y.Z -> Click Run benchmarks button
2. The binary is built, benchmarks are run.
3. When the new weights are ready, a PR is open against release-parachains-vX.Y.Z
4. We review the PR and merge it to release-parachains-vX.Y.Z

2022-04-12 10:31 UTC, NachoPal commented
What Benchmarking machine is used to run the benchmarks?

2022-04-12 10:40 UTC, alvicsam commented
`bm4`, `bm5`, `bm6`

2022-04-12 11:53 UTC, merged