bringing back repo checkout and adding a temp dir to avoid name duplication between binary and repo dir
paritytech/cumulus pull request #1299
Opened 2022-05-25 15:39 UTC by EgorPopelyaev

As it turned out we still do need to checkout a repo to be able to use scripts later in pipeline. That's why we need to introduce a temp dir where we download and run binary.

reverting changes from [1296](https://github.com/paritytech/cumulus/pull/1296)

2022-05-25 15:42 UTC, chevdor approved these changes
ok, once the Github action uses the hash for the version

2022-05-25 15:42 UTC, chevdor commented on .github/workflows/extrinsic-ordering-check-from-bin.yml
> +      - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
```

2022-05-25 17:06 UTC, sergejparity approved these changes

2022-05-25 19:21 UTC, coderobe approved these changes

2022-05-25 21:10 UTC, chevdor requested changes
If we use VARS, we should use them all the way

2022-05-25 21:10 UTC, chevdor commented on .github/workflows/extrinsic-ordering-check-from-bin.yml
> +          wget $BIN_URL -O tmp/node-bin
```suggestion
          wget $BIN_URL -O $BIN
```

2022-05-25 21:10 UTC, chevdor commented on .github/workflows/extrinsic-ordering-check-from-bin.yml
> +          pkill node-bin
Ah it hurts having to use it here.
How about:
```
BIN=node-bin
BIN_PATH=./tmp/$BIN
```
that gives you all the VARS you need to NOT type `node-bin` anywhere but at the beginning when defining the VARS.

2022-05-30 08:12 UTC, radupopa2010 approved these changes

2022-05-30 08:31 UTC, EgorPopelyaev commented
bot merge

2022-05-30 08:47 UTC, merged