Fixup benches after dir re-org
paritytech/cumulus pull request #1300
Opened 2022-05-25 16:46 UTC by gilescope

Close but no cigar. Missed out the category.

2022-05-27 10:00 UTC, chevdor requested changes
typos

2022-05-27 10:00 UTC, chevdor commented on scripts/benchmarks-ci.sh
> +benhcmarkOutput=./parachains/runtimes/$category/$runtimeName/src/weights
And I think this fix need to be propagated wherever we use `benhcmarkOutput` atm.

2022-05-27 10:58 UTC, gilescope commented on scripts/benchmarks-ci.sh
> +benhcmarkRuntimeName="$runtimeName-dev"
good spot

2022-05-27 11:04 UTC, chevdor requested changes

2022-05-27 11:04 UTC, chevdor commented on scripts/benchmarks-ci.sh
> +benchmarkOutput=./parachains/runtimes/$category/$runtimeName/src/weights
This variable is either unused and not required or we miss a rename where it is used.

2022-05-27 11:05 UTC, chevdor approved these changes

2022-05-27 11:05 UTC, chevdor commented on scripts/benchmarks-ci.sh
> +benchmarkOutput=./parachains/runtimes/$category/$runtimeName/src/weights
I take it back, just saw it.

2022-05-31 06:23 UTC, NachoPal approved these changes

2022-05-31 08:19 UTC, alvicsam approved these changes

2022-05-31 15:13 UTC, sergejparity requested changes

2022-05-31 16:24 UTC, chevdor commented on .gitlab-ci.yml
> +    - ./scripts/benchmarks-ci.sh assets westmint > ./artifacts/bench-westmint.log
If that's ok with you @sergejparity I would prefer to merge this PR as it is and asap so the benchmarks work again.
We can then line up another PR to move the scripts.
I have opened [an issue](https://github.com/paritytech/cumulus/issues/1320) to track the move.

2022-05-31 16:35 UTC, sergejparity commented on .gitlab-ci.yml
> +    - ./scripts/benchmarks-ci.sh assets westmint > ./artifacts/bench-westmint.log
Ok. No problem.

2022-05-31 16:53 UTC, sergejparity approved these changes

2022-05-31 16:53 UTC, sergejparity commented on scripts/benchmarks-ci.sh
>  for p in ${pallets[@]}
inside `./parachains/runtimes/assets/` those folders exists. So it's not needed.

2022-06-01 07:35 UTC, hbulgarini approved these changes
lgtm.

2022-06-01 07:38 UTC, joepetrowski approved these changes

2022-06-01 07:40 UTC, merged