WIP: Fixes for relnotes
paritytech/cumulus pull request #1472
Opened 2022-07-26 13:03 UTC by gilescope

better branch name than before. Continuation of https://github.com/paritytech/cumulus/pull/1471

2022-07-26 13:26 UTC, chevdor requested changes

2022-07-26 13:26 UTC, chevdor commented on .github/workflows/release-02_create-draft.yml
> +            **/context.json
The context should be part of `Archive context artifact` just below

2022-07-26 13:26 UTC, chevdor commented on scripts/ci/changelog/templates/runtime.md.tera
> +🔥 Core Version:		{{ runtime.data.runtimes.compressed.subwasm.core_version.specName }}-{{ runtime.data.runtimes.compressed.subwasm.core_version.specVersion }} ({{ runtime.data.runtimes.compressed.subw
👍 thx for that fix

2022-07-26 16:10 UTC, chevdor approved these changes

2022-07-26 16:19 UTC, radupopa2010 approved these changes

2022-08-04 10:25 UTC, chevdor approved these changes

2022-08-04 10:25 UTC, chevdor commented
bot merge

2022-08-04 10:26 UTC, merged