Integrate auto-updating parachain template on developer-hub
paritytech/cumulus pull request #1479
Opened 2022-07-28 14:08 UTC by mordamax

Fix https://github.com/paritytech/opstooling/issues/111
Example of PR: https://github.com/substrate-developer-hub/substrate-node-template/pull/363
Pipeline-script: https://github.com/paritytech/pipeline-scripts/pull/71

2022-07-28 14:15 UTC, alvicsam requested changes

2022-07-28 14:15 UTC, alvicsam commented on .gitlab-ci.yml
> +  extends:                         .docker-env
```suggestion
  extends:                         .kubernetes-env
```
It seems that the job is quite fast, we can execute it in k8s runner

2022-07-28 14:18 UTC, alvicsam approved these changes

2022-07-29 11:40 UTC, sergejparity approved these changes

2022-07-29 12:16 UTC, merged