Change CGP Topic Labels
paritytech/cumulus pull request #1988
Opened 2022-12-13 06:33 UTC by joepetrowski

Changes based on:

- Removed a "Statemint" label, because this will not scale as we add more parachains like Collectives, Bridge Hub, Staking, etc.
- Changed "CGP" to "System Parachains", as we are dropping the CGP name (worth a discussion on its own).
- Added a "Bridges" label. Why not drop this like Statemint? I see this as similar to "smart contracts", in that the issue will probably be routed to another team (e.g. Parity Bridges, Snowfork) and the changes will probably need to happen in another repo (contracts: Substrate or ink, bridges: parity-bridges, snowbridge,...).

2022-12-13 10:47 UTC, alvicsam commented
fyi, the file was moved [here](https://github.com/paritytech/labels/blob/main/docs/doc_cumulus.md)

2022-12-13 10:57 UTC, the-right-joyce requested changes
Please, add the changes to this document:
https://github.com/paritytech/labels/blob/main/ruled_labels/specs_cumulus.yaml

2022-12-20 07:08 UTC, joepetrowski commented
@the-right-joyce will the Labels repo change apply here automatically? I.e., can we close this?

2022-12-20 08:30 UTC, the-right-joyce commented
yes we can close it :)

2022-12-20 08:30 UTC, closed without merging