Fix Clippy
paritytech/cumulus pull request #2522
Opened 2023-05-04 14:26 UTC by ggwpez

Importing Polkadot Clippy config. Please add the CI job here @alvicsam

2023-05-04 14:28 UTC, ggwpez commented on pallets/collator-selection/src/weights.rs
> +			.saturating_add(Weight::from_parts(109_961_000_u64, 0).saturating_mul(r as u64))
Clippy does not seem to like the template.

2023-05-04 15:00 UTC, bkchr approved these changes

2023-05-04 15:07 UTC, chevdor approved these changes

2023-05-04 15:07 UTC, chevdor commented on .cargo/config.toml
> +]
```suggestion
]

```

2023-05-04 15:14 UTC, chevdor commented on parachains/runtimes/assets/statemint/src/xcm_config.rs
> +		matches!(
Are you sure about that one?
Using the `matches!` macro we lose the completeness check.
[Color](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6673dbf7f2227c8b1e6059051b0e371b)

2023-05-04 15:22 UTC, chevdor requested changes
Taking back my ✅
It is risky swapping `match` for the `matches!` macro where you did it.

2023-05-04 16:48 UTC, chevdor approved these changes

2023-05-04 16:56 UTC, bkchr commented
> Taking back my ✅
> It is risky swapping `match` for the `matches!` macro where you did it.

Why? The macro compiles down to the exact same code..

2023-05-04 17:01 UTC, chevdor commented
> > Taking back my ✅
> > It is risky swapping `match` for the `matches!` macro where you did it.
> 
> Why? The macro compiles down to the exact same code..

Yes but you will miss some errors if new variants have been introduced.

In that case, `match` will complain (unless a catch all `_` was used) and `matches!` will happily compile.

2023-05-04 19:11 UTC, bkchr commented
> Yes but you will miss some errors if new variants have been introduced.
> 
> In that case, `match` will complain (unless a catch all `_` was used) and `matches!` will happily compile.

It will just return `false` for new variants that are not explicitly matched on. So, it is secure and nothing breaks or allows something accidentally.

2023-05-05 08:05 UTC, skunert approved these changes

2023-05-05 08:35 UTC, alvicsam approved these changes

2023-05-05 09:27 UTC, bkchr commented
bot rebase

2023-05-05 22:53 UTC, ggwpez commented
bot rebase

2023-05-06 06:01 UTC, merged