add test-utils feature to polkadot-node-core-pvf
paritytech/cumulus pull request #2989
Opened 2023-08-09 19:44 UTC by Jpserrat

Polkadot companion: https://github.com/paritytech/polkadot/pull/7538

2023-08-09 19:46 UTC, paritytech-cicd-pr commented
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable
**Logs**: https://gitlab.parity.io/parity/mirrors/cumulus/-/jobs/3355425

2023-08-11 11:17 UTC, Jpserrat commented
@mrcnski @slumber Cumulus companion created.

2023-08-11 13:38 UTC, mrcnski approved these changes

2023-08-11 13:40 UTC, slumber approved these changes

2023-08-14 10:12 UTC, mrcnski commented
Agh! I'll try to fix your companion. Luckily companions won't be a thing anymore soon.

2023-08-14 11:11 UTC, ggwpez commented
Green now. Can we merge to unblock the CI?

2023-08-14 11:13 UTC, ggwpez commented on Cargo.lock
> +version = "0.1.26"
Why is this updating so many deps?

2023-08-14 11:15 UTC, ggwpez requested changes
I think something with the update is wrong with the cargo update. It should be -+300 lines, not 2200.

2023-08-14 11:24 UTC, mrcnski commented
@ggwpez What command should I run? I'm getting

```
$ cargo update
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/substrate`
    Updating git repository `https://github.com/paritytech/polkadot`
error: no matching package named `pallet-multisig` found
location searched: https://github.com/paritytech/substrate?branch=master
required by package `asset-hub-kusama-runtime v0.9.420 (/Users/parity/Repos/github.com/paritytech/cumulus-2/parachains/runtimes/assets/asset-hub-kusama)`
```

2023-08-14 11:26 UTC, ggwpez commented
Need this first, there is some upstream problem in Substrate master https://github.com/paritytech/substrate/pull/14763

2023-08-14 11:28 UTC, mrcnski commented
Got it thanks. Hopefully this is the last companion I ever have to merge. 😄

2023-08-14 11:54 UTC, ggwpez approved these changes
I reverted the last updates, this is roughly how it should look like; not +-2200.

![image](https://github.com/paritytech/cumulus/assets/10380170/0ab157a7-5f13-49d9-93ff-56450234d0c2)

2023-08-14 11:55 UTC, mrcnski commented
Thanks @ggwpez! I had tried reverting Cargo.lock then `cargo update`, but guess I messed up something.

2023-08-14 12:42 UTC, merged