Adds a mock provider for the parachain inherent
paritytech/cumulus pull request #484
Opened 2021-06-08 20:38 UTC by JoshOrndorff

This PR introduces an inherent data provider for the parachain inherent that provides minimal data. This is useful for testing your parachain runtime in a lighter context than spinning up a full relay chain.

This provider includes a minimal storage proof, and a mocked relay chain block number. The parameters of how the relay chain block number is mocked are tunable.

This is groundwork for https://github.com/paritytech/cumulus/issues/483

2021-06-09 14:37 UTC, bkchr requested changes
All of this should just be in a mock.rs in the inherent crate.

2021-06-10 20:26 UTC, JoshOrndorff commented
Okay, I've moved it where you asked. The reason I made a separate crate was to not make $466 worse. But I agree this should live here.

2021-06-12 12:27 UTC, bkchr requested changes
You need to put `mod mock.rs` into the lib.rs file

2021-06-23 08:37 UTC, bkchr approved these changes

2021-06-23 08:37 UTC, merged