Refactor paths and runtime names
paritytech/cumulus pull request #507
Opened 2021-06-24 12:54 UTC by chevdor

This PR renames the rococo runtime to follow the pattern used by all other chains.
It also uses the same folder tree (= runtimes under a `runtime`) folder. That simplifies tooling and allows building all the runtimes the same way.

2021-06-24 14:14 UTC, bkchr requested changes
I would be fine to move this to `polkadot-parachains/runtime/*`, but not moving it to the top

2021-06-24 14:25 UTC, chevdor commented
That works for me. The most important is that:
- the rococo runtime is named `rococo-runtime`
- the runtime `<foobar>` in the `runtime_dir` (in our case `polkadot-parachains` or `polkadot-parachains/runtimes`) as a `foobar` folder (vs `foobar-runtime` currently).

It is easier if the `runtime_dir` is a folder called `runtime` as in Polkadot but having it a level down as you suggest is not a big issue. 

Let me adjust to your suggestion.

2021-06-24 14:48 UTC, chevdor commented
I don't see a benefit going from `polkadot-parachains/*` to `polkadot-parachains/runtime/*` so I will bring the runtimes back to `polkadot-parachains/*`

2021-06-24 16:20 UTC, chevdor commented
@bkchr would that work for you now ?

2021-06-28 11:09 UTC, bkchr approved these changes

2021-06-28 11:09 UTC, bkchr commented on polkadot-parachains/Cargo.toml
> +shell-runtime = { package = "shell-runtime", path = "shell" }
```suggestion
shell-runtime = { path = "shell" }
```

2021-06-28 11:09 UTC, bkchr commented
bot merge

2021-06-28 12:24 UTC, merged