Add build with docker info to README
paritytech/cumulus pull request #609
Opened 2021-09-14 08:53 UTC by alvicsam

Added information about how to build and test the code with a docker image that is used in our pipelines. (Related to https://github.com/paritytech/ci_cd/issues/113)

2021-09-14 09:05 UTC, bkchr approved these changes

2021-09-14 09:28 UTC, chevdor requested changes
I think we can make it a little simpler but no big issues.

2021-09-14 09:28 UTC, chevdor commented on README.md
> +git clone https://github.com/paritytech/cumulus
I think we can assume that the user cloned the repo and is in the proper folder. The previous commands (`cargo build`...) do assume that.
 
If we **really** want to explain how to clone the repo (I would suggest not to, as it adds maintenance if the repo moves or gets renamed) we could have a section at the beginning.

2021-09-14 09:28 UTC, chevdor commented on README.md
> +docker pull paritytech/ci-linux:production
```suggestion
docker pull paritytech/ci-linux:production
```

We don't really need that, the `docker run` will pull as needed.

2021-09-14 09:28 UTC, chevdor commented on README.md
> +                    paritytech/ci-linux:production cargo build --release -p polkadot-collator
```suggestion
                    paritytech/ci-linux:production cargo build --release --locked -p polkadot-collator
```

2021-09-14 10:41 UTC, chevdor commented on README.md
> +                    paritytech/ci-linux:production cargo build --release -p polkadot-collator
yes

2021-09-14 10:42 UTC, chevdor approved these changes
All good once the additionnal missing `--locked` you spoted has been added.

2021-09-16 08:07 UTC, chevdor approved these changes

2021-09-16 08:19 UTC, alvicsam commented
@chevdor unfortunately I can't merge changes (the button is inactive), tests are failing. I restarted them several times but with no luck (interesting thing it that each time different tests are failing)

2021-09-16 08:23 UTC, chevdor commented
@alvicsam yes I saw that. I just approved **again** after checking that you did the last changes we talked about. 
Don't worry about it the build failing. Your PR has nothing to do with it.
This will be fixed or your PR will be merged "as is". We just need to be patient :)

2021-09-16 09:49 UTC, merged