Add fmt and clippy
paritytech/cumulus pull request #616
Opened 2021-09-16 09:13 UTC by alvicsam

Can I suggest using gitlab-ci instead of GHA?

Related to:
https://github.com/paritytech/cumulus/issues/614
https://github.com/paritytech/cumulus/pull/615

2021-09-16 09:18 UTC, chevdor commented
What would be the benefit in this case ?

2021-09-16 09:21 UTC, alvicsam commented
> What would be the benefit in this case ?

Almost all our projects use gitlab-ci and in future we want to have unified pipeline for all projects (at least the repeatable steps). So it's better to have one unified instrument for CI.

2021-09-16 09:25 UTC, alvicsam commented
Found out that `paritytech/ci-linux` doesn't have not fmt, nor clippy >_<
But I'll fix it.

2021-09-16 09:29 UTC, chevdor commented
For now, I am mainly working on fixing the issues related to those checks. 

Whether we do the checks in github or gitlab can be discussed. I would prioritize simplicity and speed, this is why I went for GHA since this is supposed to be a **quick** check and not a big mechanics. 

Ultimately, I don't mind but I find GHA more convenient for those, especially because we could have one Github Action that we use adn reused in most repos.

For big and heavy runs, I am with you on the choice of gitlab though.

NOTE: In your pipeline, you should run `fmt` first as it runs much faster and thus can fail much faster.

2021-09-16 09:48 UTC, alvicsam commented
`fmt` took 2 minutes, so it's relatively quick :) And it's just 5 lines in `.giltab-ci.yml`

>NOTE: In your pipeline, you should run fmt first as it runs much faster and thus can fail much faster.

Currently they are in one stage, so they run simultaneously. 

p.s. still need to add clippy to ci image

2021-09-16 11:30 UTC, rcny requested changes

2021-09-16 11:30 UTC, rcny commented on .gitlab-ci.yml
> +  <<:                              *docker-env
`&docker-env` refers to `linux-docker` runners - we use them for heavyweight jobs (e.g. compilation stuff). These runners have limited capacity. Please resort to `&kubernetes-env` (`kubernetes-parity-build`) instead.

2021-09-16 11:30 UTC, rcny commented on .gitlab-ci.yml
> +  <<:                              *docker-env
Same as above.

2021-09-16 11:36 UTC, rcny commented
`&kubernetes-env` lacks `image: "${CI_IMAGE}"` directive.

2021-09-16 11:42 UTC, rcny approved these changes

2021-09-19 12:24 UTC, bkchr commented
Already done. Ty anyway. 

I know that this runs stuff on gitlab,but I don't see any advantage in this anyway, so I'm going to close this pr.

2021-09-19 12:24 UTC, closed without merging