Add check_labels script and workflow
paritytech/cumulus pull request #782
Opened 2021-11-22 14:35 UTC by chevdor

This PR adds the same `check_labels` check for PRs.

2021-11-25 19:44 UTC, TriplEight requested changes
I suggest it's better to avoid doubling the maintenance and move these files to some common source like https://github.com/paritytech/pipeline-scripts

2021-11-25 20:03 UTC, chevdor commented
Yes, that would be ideal. I would love however to have something in place asap because right now, we have nothing in place. Would that be ok to merge this version and think about an upgrade ?
Also keep in mind that that repos are different so the rules may be(come) different.

I have ideas to improve the topic but I would like to first have *something* in place.

2021-12-06 14:23 UTC, TriplEight commented
@chevdor I'm OK with merging this, but please create a follow-up issue, mentioning where the instances of the script should be substituted with an importable version. And certainly with your ideas, too! I think the right place for the issue should be here https://github.com/paritytech/opstooling/issues/

2021-12-06 14:23 UTC, TriplEight approved these changes

2021-12-06 14:30 UTC, merged